core/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    re_path(r'^\.well-known/', include('letsencrypt.urls')),
    re_path(r'^favicon\.ico$', favicon_view),
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('captcha/', include('captcha.urls')),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('menu/', views.MenuView.as_view(), name='menu'),
    path('gallery/', views.GalleryPageView.as_view(), name='gallery'),
    path('finedining/', views.FineDiningView.as_view(), name='finedining'),
    path('custom-dining/', views.CustomDiningView.as_view(), name='customdining'),
    path('hire-a-chef/', views.HireAChefView.as_view(), name='hire_a_chef'),
    path('hire-a-chef/successful', views.HireAChefSuccessfulView.as_view(), name='hire_a_chef_success'),
    path('custom-dining/successful/', views.CustomDiningSuccessView.as_view(), name='customdining-successful'),
    path('finedining/successful/', views.FineDiningSuccessful.as_view(), name='finedining_success'),
    path('casual-dining/', views.CasualDiningView.as_view(), name='casual_dining'),
    path('casual-dining/successful/', views.CasualDiningSuccessfulView.as_view(), name='casual_dining_success'),
    # path('reserve/', views.make_reservation, name='reserve')
]

pages/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/dark-mode.css' %}">
    <!-- <link rel="shortcut icon" href="{% static 'images/ose-favicon.png' %}" type="image/x-icon"> -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
    {% block styling %}{% endblock %}
</head>
<body data-bs-spy="scroll" data-bs-target="#bsb-tpl-navbar" data-bs-smooth-scroll="true" tabindex="0" class="min-vh-100">
    <!-- Header -->
    <header id="header" class="sticky-top bsb-tpl-header-sticky bsb-tpl-header-sticky-animationX">
        {% include 'nav.html' %}
    </header>
    {% block content %}{% endblock %}

    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

pages/templates/footer.html
<!-- Footer -->

<footer class="footer mt-auto d-flex flex-wrap justify-content-between align-items-center py-3 my-4 mx-5 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <span class="text-black">© 2024 Ose Dining | +234 816 747 6771</span>
    </div>

    <ul class="nav col-md-4 justify-content-end pr-8 list-unstyled d-flex">
      <li class="ms-3">
        <a href="" class="text-reset">
          <i class="bi bi-facebook"></i>
        </a>
      </li>
      <li class="ms-3">
        <a href="https://www.instagram.com/osedining/" class="text-reset">
          <i class="bi bi-instagram"></i>
        </a>
      </li>
    </ul>
</footer>

pages/templates/nav.html
{% load static %}
<!-- Navbar 1 - Bootstrap Brain Component -->
<nav id="scrollspyNav" class="navbar navbar-expand-lg bg-dark bg-black bsb-navbar bsb-navbar-hover bsb-navbar-caret bsb-tpl-navbar-sticky" 
data-bsb-sticky-target="#header" data-bs-theme="dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'pages:home' %}">
      <img src="{% static 'images/white-logo.png' %}" class="bsb-tpl-logo" alt="">
    </a>
    <button class="navbar-toggler border-0" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
      </svg>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul id="bsb-tpl-navbar" class="navbar-nav justify-content-end flex-grow-1">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'pages:home' %}" aria-current="page">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dinings
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'pages:finedining' %}">Fine Dining</a></li>
              <li><a class="dropdown-item" href="{% url 'pages:casual_dining' %}">Casual Dining</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'pages:customdining' %}">Customised Dining</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:gallery' %}">Gallery</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:contact' %}">Contact</a>
          </li>
          <li class="nav-item">
            <a class="btn btn-outline-light bsb-btn-2xl" href="{% url 'pages:hire_a_chef' %}">Hire A Chef</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>