core/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    re_path(r'^\.well-known/', include('letsencrypt.urls')),
    re_path(r'^favicon\.ico$', favicon_view),
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('captcha/', include('captcha.urls')),
]

pages/models.py
from django.db import models

class Contact(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    date_send = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

class BaseRequest(models.Model):
    your_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    email = models.EmailField(blank=True, null=True)
    date = models.DateField()
    time = models.TimeField()
    location = models.CharField(max_length=255)
    date_send = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class Hire(BaseRequest):

    EVENT_TYPE = (
        ('HOME', 'Home'),
        ('WEDDING', 'Wedding'),
        ('BIRTHDAY', 'Birthday'),
        ('ANNIVERSARY', 'Anniversary'),
        ('OTHERS', 'Others'),
    )

    event_type = models.CharField(max_length=15, choices=EVENT_TYPE, default='HOME')
    additional_information = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'Hire request by {self.your_name}'

class CustomisedDining(BaseRequest):
    service_details = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'Custom menu request by {self.your_name}'

class BaseDining(models.Model):
    your_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    email = models.EmailField(blank=True, null=True)
    date = models.DateField()
    time = models.TimeField()
    location = models.CharField(max_length=255)
    number_of_guest = models.IntegerField(default=10)
    additional_information = models.TextField(blank=True, null=True)
    date_send = models.DateTimeField(auto_now_add=True)

    we_are_allowed_to_take_pictures_of_you_and_your_guest = models.BooleanField(default=True, db_column="picture_consent")
    we_are_allowed_to_take_pictures_of_your_apartment = models.BooleanField(default=True, db_column="apartment_consent")
    we_are_allowed_to_use_your_event_content_for_our_business_promotions = models.BooleanField(default=True, db_column="content_consent")

    class Meta:
        abstract = True

    def __str__(self):
        return self.your_name
    

class FineDining(BaseDining):
    GUEST_NUMBER = (
        ('10', '10 or less'),
        ('20', '20 or less'),
        ('30', '30 or less'),
        ('40', '40 or less'),
        ('50', '50 or more'),
    )

    MENUS = (
        ('M1', 'Menu 1'),
        ('M2', 'Menu 2'),
        ('M3', 'Menu 3'),
        ('M4', 'Menu 4'),
        ('M5', 'Menu 5'),
        ('M6', 'Menu 6'),
        ('M7', 'Menu 7'),
    )

    # number_of_guest = models.CharField(max_length=2, choices=GUEST_NUMBER, default=10)
    menu_type = models.CharField(max_length=2, choices=MENUS, default='M1')


class CasualDining(BaseDining):
    BREAD = (
        ('F', 'Focaccia'),
        ('C', 'Ciabatta'),
        ('S', 'Sourdough'),
        ('H', 'Herbal bun'),
        ('G', 'Garlic bread'),
        ('CH', 'Challah'),
    )

    GUEST_NUMBER = (
        ('8', '8 or less'),
        ('15', '15 or less'),
        ('20', '20 or less'),
        ('30', '30 or less'),
        ('40', '40 or more'),
    )

    MENUS = (
        ('M1', 'Menu 1'),
        ('M2', 'Menu 2')
    )

    SIDES = (
        ('BMP', 'Buttering mashed potatoes'),
        ('CGP', 'Cheesy garlic roasted butter potatoes'),
        ('PF', 'Potatoes fondant'),
        ('CBP', 'Creamy baby potatoes'),
        ('SPR', 'OSE special fried rice'),
        ('SSF', 'Spaghetti stir fry'),
        ('CJ', 'Coriander jasmine'),
        ('SAJ', 'Smoked asun jollof '),

    )

    VEGETABLES = (
        ('RC', 'Roasted carrot'),
        ('BT', 'Broccoli tempura'),
        ('SM', 'Sautéed mushroom'),
        ('PO', 'Pickled onion'),
        ('MP', 'Mixed bell pepper'),
        ('SS', 'Sautéed spinach'),
        ('AB', 'Assorted bread'),
    )

    # number_of_guest = models.CharField(max_length=2, choices=GUEST_NUMBER, default='8')
    menu_type = models.CharField(max_length=2, choices=MENUS, default='M1')
    bread = models.CharField(max_length=2, choices=BREAD, default='F')
    side_one = models.CharField(max_length=3, choices=SIDES, default='BMP')
    side_two = models.CharField(max_length=3, choices=SIDES, default='CGP')

    vegetable_one = models.CharField(max_length=2, choices=VEGETABLES, default='RC')
    vegetable_two = models.CharField(max_length=2, choices=VEGETABLES, default='BT')

pages/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import (Contact,
                     FineDining,
                     CasualDining,
                     CustomisedDining,
                     Hire)

class ContactForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Contact
        exclude = ['date_send']


class CustomDiningForm(forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))
    class Meta:
        model = CustomisedDining
        fields = ['your_name', 'phone', 'email', 'date', 'time', 'location', 'service_details']


class FineDiningForm(forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))
    additional_information = forms.CharField(widget=forms.Textarea(attrs={'name':'body', 'rows':3, 'cols':5, 'placeholder':'Kindly specify any alergies or special needs.'}))
    class Meta:
        model = FineDining
        fields = ['menu_type', 'date', 'time','your_name', 'phone', 'email', 'location', 'number_of_guest', 
                  'we_are_allowed_to_take_pictures_of_you_and_your_guest',
                  'we_are_allowed_to_take_pictures_of_your_apartment',
                  'we_are_allowed_to_use_your_event_content_for_our_business_promotions',
                  'additional_information']
        


class CasualDiningForm(forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))
    additional_information = forms.CharField(widget=forms.Textarea(attrs={'name':'body', 'rows':3, 'cols':5, 'placeholder':'Kindly specify any alergies or special needs.'}))
    class Meta:
        model = CasualDining
        fields = ['menu_type', 'date', 'time','your_name', 'phone', 'email', 
                    'location', 'number_of_guest', 'bread',
                  'side_one', 'side_two', 'vegetable_one', 'vegetable_two',
                  'we_are_allowed_to_take_pictures_of_you_and_your_guest',
                  'we_are_allowed_to_take_pictures_of_your_apartment',
                  'we_are_allowed_to_use_your_event_content_for_our_business_promotions',
                  'additional_information']

class HireForm(forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))
    additional_information = forms.CharField(widget=forms.Textarea(
        attrs={'name':'body',
               'rows':3, 'cols':5,
               'placeholder':'Kindly specify additional information about the chef job.'}))
    class Meta:
        model = Hire
        exclude = ['date_send']

pages/templates/forms/casualdining.html
<div class="">
    <div class="modal-body">
        {% csrf_token %}
        
        <div class="form-group">
            <label class="control-label  " for="id_menu_type">Menu type</label>
            <div class=" ">
                <select name="menu_type" class=" form-control" id="id_menu_type">
                    <option value="M1" selected="">Menu 1</option>
                    <option value="M2">Menu 2</option>
                </select>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label  " for="id_date">Date</label>
            <div class=" ">
                <input type="date" name="date" class=" form-control" required="" id="id_date">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label  " for="id_time">Time</label>
            <div class=" ">
                <input type="time" name="time" class=" form-control" required="" id="id_time">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label  " for="id_your_name">Your name</label>
            <input type="text" name="your_name" maxlength="255" class=" form-control" required="" id="id_your_name">
        </div>
        
        <div class="form-group">
            <label class="control-label  " for="id_phone">Phone</label>
            <input type="text" name="phone" maxlength="255" class=" form-control" required="" id="id_phone">
        </div>
        
        <div class="form-group">
            <label class="control-label  " for="id_email">Email</label>
            <input type="email" name="email" maxlength="254" class=" form-control" id="id_email">
        </div>

        <div class="form-group">
            <label class="control-label  " for="id_location">Location</label>
            <input type="text" name="location" maxlength="255" class=" form-control" required="" id="id_location">
        </div>

        <div class="form-group">
            <label class="control-label  " for="id_number_of_guest">Number of guest</label>
    
            <select name="number_of_guest" class=" form-control" id="id_number_of_guest">
                <option value="8" selected="">8 or less</option>
                <option value="15">15 or less</option>
                <option value="20">20 or less</option>
                <option value="30">30 or less</option>
                <option value="40">40 or more</option>
            </select>
        </div>
        
        <div class="form-group">
            <label class="control-label  " for="id_bread">Bread</label>
    
            <select name="bread" class=" form-control" id="id_bread">
                <option value="F" selected="">Focaccia</option>
                <option value="C">Ciabatta</option>
                <option value="S">Sourdough</option>
                <option value="H">Herbal bun</option>
                <option value="G">Garlic bread</option>
                <option value="CH">Challah</option>
            </select>
        </div>
        
        <div class="form-group">
            <label class="control-label  " for="id_side_one">Side one</label>
    
            <select name="side_one" class=" form-control" id="id_side_one">
                <option value="BMP" selected="">Buttering mashed potatoes</option>
                <option value="CGP">Cheesy garlic roasted butter potatoes</option>
                <option value="PF">Potatoes fondant</option>
                <option value="CBP">Creamy baby potatoes</option>
                <option value="SPR">OSE special fried rice</option>
                <option value="SSF">Spaghetti stir fry</option>
                <option value="CJ">Coriander jasmine</option>
                <option value="SAJ">Smoked asun jollof </option>
            </select>
        </div>
        
        <div class="form-group">
            <label class="control-label  " for="id_side_two">Side two</label>
    
            <select name="side_two" class=" form-control" id="id_side_two">
                <option value="BMP">Buttering mashed potatoes</option>
                <option value="CGP" selected="">Cheesy garlic roasted butter potatoes</option>
                <option value="PF">Potatoes fondant</option>
                <option value="CBP">Creamy baby potatoes</option>
                <option value="SPR">OSE special fried rice</option>
                <option value="SSF">Spaghetti stir fry</option>
                <option value="CJ">Coriander jasmine</option>
                <option value="SAJ">Smoked asun jollof </option>
            </select>
        </div>
        
        <div class="form-group">
            <label class="control-label  " for="id_vegetable_one">Vegetable one</label>
    
            <select name="vegetable_one" class=" form-control" id="id_vegetable_one">
                <option value="RC" selected="">Roasted carrot</option>
                <option value="BT">Broccoli tempura</option>
                <option value="SM">Sautéed mushroom</option>
                <option value="PO">Pickled onion</option>
                <option value="MP">Mixed bell pepper</option>
                <option value="SS">Sautéed spinach</option>
                <option value="AB">Assorted bread</option>
            </select>
        </div>
        
        <div class="form-group">
            <label class="control-label  " for="id_vegetable_two">Vegetable two</label>
            
            <select name="vegetable_two" class=" form-control" id="id_vegetable_two">
                <option value="RC">Roasted carrot</option>
                <option value="BT" selected="">Broccoli tempura</option>
                <option value="SM">Sautéed mushroom</option>
                <option value="PO">Pickled onion</option>
                <option value="MP">Mixed bell pepper</option>
                <option value="SS">Sautéed spinach</option>
                <option value="AB">Assorted bread</option>
            </select>
        </div>
        
        <div class="form-group">
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="we_are_allowed_to_take_pictures_of_you_and_your_guest" id="id_we_are_allowed_to_take_pictures_of_you_and_your_guest" checked=""> <span>We are allowed to take pictures of you and your guest</span>
                </label>
            </div>
        </div>
        
        <div class="form-group">
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="we_are_allowed_to_take_pictures_of_your_apartment" id="id_we_are_allowed_to_take_pictures_of_your_apartment" checked=""> <span>We are allowed to take pictures of your apartment</span>
                </label>
            </div>
        </div>
        
        <div class="form-group">
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="we_are_allowed_to_use_your_event_content_for_our_business_promotions" id="id_we_are_allowed_to_use_your_event_content_for_our_business_promotions" checked=""> <span>We are allowed to use your event content for our business promotions</span>
                </label>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label  " for="id_additional_information">Additional information</label>
            <textarea name="additional_information" cols="5" rows="3" placeholder="Kindly specify any alergies or special needs." class=" form-control" required="" id="id_additional_information"></textarea>
        </div>
    </div>
</div>