core/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    re_path(r'^\.well-known/', include('letsencrypt.urls')),
    re_path(r'^favicon\.ico$', favicon_view),
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('captcha/', include('captcha.urls')),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('menu/', views.MenuView.as_view(), name='menu'),
    path('gallery/', views.GalleryPageView.as_view(), name='gallery'),
    path('finedining/', views.FineDiningView.as_view(), name='finedining'),
    path('custom-dining/', views.CustomDiningView.as_view(), name='customdining'),
    path('hire-a-chef/', views.HireAChefView.as_view(), name='hire_a_chef'),
    path('hire-a-chef/successful', views.HireAChefSuccessfulView.as_view(), name='hire_a_chef_success'),
    path('custom-dining/successful/', views.CustomDiningSuccessView.as_view(), name='customdining-successful'),
    path('finedining/successful/', views.FineDiningSuccessful.as_view(), name='finedining_success'),
    path('casual-dining/', views.CasualDiningView.as_view(), name='casual_dining'),
    path('casual-dining/successful/', views.CasualDiningSuccessfulView.as_view(), name='casual_dining_success'),
    # path('reserve/', views.make_reservation, name='reserve')
]

pages/templates/pages/about.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}

{% block title %}Ose Dining - About Us{% endblock %}
{% block styling %}<link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.3/components/abouts/about-1/assets/css/about-1.css" />{% endblock %}

{% block content %}
<!-- About 1 - Bootstrap Brain Component -->
<main>
	<section class="py-3 py-md-5 py-xl-8">
		<div class="container">
		  <div class="row gy-3 gy-md-4 gy-lg-0 align-items-lg-center">
			<div class="col-12 col-lg-6 col-xl-5">
			  <img class="img-fluid rounded" loading="lazy" src="/static/images/food2.png" alt="">
			</div>
			<div class="col-12 col-lg-6 col-xl-7">
			  <div class="row justify-content-xl-center">
				<div class="col-12 col-xl-11">
				  <h2 class="h1 mb-2">Who Are We?</h2>
				  <p class="lead fs-10 text-secondary mb-2">OSSE Dining offers exclusive private dining experiences, bringing its kitchen directly to clients' chosen locations for optimal comfort and convenience.</p>
				  <p class="mb-2">OSSE Dining recognizes the cultural, traditional, and stylistic importance of food in everyone's lives, aiming to illuminate each individual's unique food narrative.</p>
				  <p class="mb-5">The culinary team at OSSE is driven by a deep passion for excellence, crafting innovative recipes with dedication, affection, and extensive experience.</p>
				  <div class="row gy-4 gy-md-0 gx-xxl-5X">
					<div class="col-12 col-md-6">
					  <div class="d-flex">
						<div>
						  <h4 class="mb-3">Our Magnificent Main Course</h4>
						  <p class="text-secondary mb-0">At OSE Dining embodies exclusivity, cultural richness, and professional presentation. It's simple, tasteful, and elegant, with rich flavors that reflect our culinary excellence.</p>
						</div>
					  </div>
					</div>
					<div class="col-12 col-md-6">
					  <div class="d-flex">
						<div>
						  <h4 class="mb-3">Dessert Glory</h4>
						  <p class="text-secondary mb-0">Desserts, made with love and inspired by street snacks, heritage, and childhood tastes, offer memorable treats like banana cake bites, agbalumo syrup, kilishi gelato, and dankwa tuile.</p>
						</div>
					  </div>
					</div>
				  </div>
				</div>
			  </div>
			</div>
		  </div>
		</div>
	</section>
</main>

{% endblock %}

pages/templates/pages/contact.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}

{% block title %}Ose Dinning - Contact Us{% endblock %}

{% block content %}
<main id="main">
    <!-- Service 6 - Bootstrap Brain Component -->
    <section id="scrollspyServices" class="bsb-service-6 py-5 py-xl-8 bsb-section-py-xxl-1">
        <div class="container">
          <div class="row justify-content-md-center">
            <div class="col-12 col-md-10 col-lg-8 col-xl-7">
              <h3 class="fs-6 mb-2 text-secondary text-center text-uppercase">Contact Us</h3>
              <h2 class="display-5 mb-1 mb-md-3 text-center">Get In Touch</h2>
              <hr class="w-50 mx-auto mb-2 mb-xl-5 border-dark-subtle">
            </div>
          </div>
        </div>
  
        <div class="container overflow-hidden">
          <div class="row gy-2 gy-md-0 gx-xxl-3">
            <div class="col-12 col-md-12">
              <div class="card bg-transparent border-primary rounded-0 overflow-hidden">
                <div class="card-body">
                  <!-- Print form errors -->
                  {% if form.errors %}
                    <div class="alert alert-danger" role="alert">
                      <strong>Oops!</strong> There was an error processing your request.
                      <ul>
                        {% for field in form %}
                          {% for error in field.errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        {% endfor %}
                      </ul>
                    </div>
                  {% endif %}
                  
                  
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form|bootstrap }}
                        
                        <div class="form-actions">
                            <button type="submit" class="btn btn-outline-dark mt-2 mb-2">Send</button>
                        </div>
                    </form>
                  <div class="bsb-circle bg-accent border border-4 border-accent position-absolute top-100 start-100 translate-middle"></div>
                </div>
              </div>
            </div>
      </section>
</main>

{% endblock %}

pages/templates/pages/gallery.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}

{% block title %}Ose Dinning | Works{% endblock %}
{% block styling %}<link rel="stylesheet" href="{% static 'css/gallery.css' %}">
<link rel="stylesheet" href="{% static 'css/lightbox.css' %}">
{% endblock %}

{% block content %}
<main>
    <div class="container">
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining1.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining1.webp' %}" alt="Image Gallery">
            </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining25.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining25.webp' %}" alt="Image Gallery">
            </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining26.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining26.webp' %}" alt="Image Gallery">
            </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining24.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining24.webp' %}" alt="Image Gallery">
            </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining2.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining2.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining6.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining6.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining3.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining3.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining7.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining7.webp' %}" alt="Image Gallery">
            </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining40.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining40.webp' %}" alt="Image Gallery">
            </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining5.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining5.webp' %}" alt="Image Gallery">
            </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining8.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining8.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining9.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining9.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
              <a href="{% static 'images/works/dining12.webp' %}" data-lightbox="Our Works">
              <img src="{% static 'images/works/dining12.webp' %}" alt="Image Gallery">
            </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining4.webp' %}" data-lightbox="Our Works">
              <img src="{% static 'images/works/dining4.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining15.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining15.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>

        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining16.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining16.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining17.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining17.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining18.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining18.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining19.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining19.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining20.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining20.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining21.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining21.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining34.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining34.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining31.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining31.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining32.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining32.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining33.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining33.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining35.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining35.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining36.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining36.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining37.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining37.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining38.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining38.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
        <div class="card">
          <div class="card-image">
            <a href="{% static 'images/works/dining41.webp' %}" data-lightbox="Our Works">
            <img src="{% static 'images/works/dining41.webp' %}" alt="Image Gallery">
          </a>
          </div>
        </div>
      </div>
</main>

<script src="{% static 'js/lightbox-plus-jquery.js' %}"></script>
{% endblock %}

pages/templates/pages/hire-a-chef.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}

{% block title %}Ose Dining - Hire A Chef{% endblock %}

{% block content %}
<main id="main">
    <!-- Section - Services -->
    <!-- Service 6 - Bootstrap Brain Component -->
    <section id="scrollspyServices" class="bsb-service-6 py-5 py-xl-8 bsb-section-py-xxl-1">
        <div class="container">
          <div class="row justify-content-md-center">
            <div class="col-12 col-md-10 col-lg-8 col-xl-7">
              <h3 class="fs-6 mb-2 text-secondary text-center text-uppercase">Hire A Chef</h3>
              <h2 class="display-5 mb-1 mb-md-3 text-center">Unforgettable Dining Experiences at Home</h2>
              <hr class="w-50 mx-auto mb-2 mb-xl-5 border-dark-subtle">
            </div>
          </div>
        </div>
  
        <div class="container overflow-hidden">
          <div class="row gy-2 gy-md-0 gx-xxl-3">
            <div class="col-12 col-md-12">
              <div class="card bg-transparent border-primary rounded-0 overflow-hidden">
                <div class="card-body">
                  
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form|bootstrap }}
                        
                        <div class="form-actions">
                            <button type="submit" class="btn btn-outline-dark mt-2 mb-2">Send Request</button>
                        </div>
                    </form>
                  <div class="bsb-circle bg-accent border border-4 border-accent position-absolute top-100 start-100 translate-middle"></div>
                </div>
              </div>
            </div>
      </section>
</main>

{% endblock %}

pages/templates/pages/hire-successful.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Ose Dinning - Hire A Chef{% endblock %}

{% block content %}
<main class="container contact-ctn text-center mt-5">
    <svg xmlns="http://www.w3.org/2000/svg" width="150" height="150" fill="currentColor" class="bi bi-chat-left-quote" viewBox="0 0 16 16">
        <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
        <path d="M7.066 4.76A1.665 1.665 0 0 0 4 5.668a1.667 1.667 0 0 0 2.561 1.406c-.131.389-.375.804-.777 1.22a.417.417 0 1 0 .6.58c1.486-1.54 1.293-3.214.682-4.112zm4 0A1.665 1.665 0 0 0 8 5.668a1.667 1.667 0 0 0 2.561 1.406c-.131.389-.375.804-.777 1.22a.417.417 0 1 0 .6.58c1.486-1.54 1.293-3.214.682-4.112z"/>
    </svg>
    <h1>Message Sent</h1>
    <p>Your form submission was successful! <br>
        We will reachout to you soon.
    </p>
    <a href="" class="btn btn-primary mb-5">Explore our menu</a>
</main>


{% endblock %}

pages/templates/pages/home.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}

{% block title %}Ose Dinning - Home{% endblock %}

{% block content %}
<!-- Main -->
<main id="main">
    <!-- Hero 3 - Bootstrap Brain Component -->
    <section id="scrollspyHero" class="bg-black text-white pt-2 pb-5 p-lg-0">
        <div class="container overflow-hidden">
        <div class="row gy-5 gy-lg-0 align-items-lg-center justify-content-lg-between">
            <div class="col-12 col-lg-6 order-1 order-lg-0">
            <h1 class="display-3 fw-bold mb-3 animate__animated animate__backInDown">EQUISITE &amp; DELICIOUS</h1>
            <p class="fs-4 mb-3 animate__animated animate__backInDown animate__delay-1s">Our passion for exceptional food has inspired ingenious recipes, 
                crafted with dedication, care, and expertise. 
                OSE dining would offer you an experience which enables you to share and savor stories through food.</p>
            <div class="d-grid gap-2 d-sm-flex animate__animated animate__backInDown animate__delay-2s">
                <a href="{% url 'pages:contact' %}" class="btn btn-warning bsb-btn-3xl btn-lg">Drop a message</a>
            </div>
            </div>
            <div class="col-12 col-lg-5 text-center">
            <div class="position-relative">
                <div class="bsb-circle border border-4 border-warning position-absolute top-50 start-10 translate-middle z-1"></div>
                <div class="bsb-circle bg-primary position-absolute top-50 start-50 translate-middle" style="--bsb-cs: 460px;"></div>
                <div class="bsb-circle border border-4 border-warning position-absolute top-10 end-0 z-1" style="--bsb-cs: 100px;"></div>
                <img class="img-fluid position-relative z-2 food-animate rounded-circle" loading="lazy" src="https://i.ibb.co/RpGgXgg/hero.webp" alt="Hero-image" style="margin-top: 2rem;">
            </div>
            </div>
        </div>
        </div>
    </section>


    

    <!-- Section - Services -->
    <!-- Service 6 - Bootstrap Brain Component -->
    <section id="scrollspyServices" class="bsb-service-6 py-5 py-xl-8 bsb-section-py-xxl-1 animate__animated">
      <div class="container">
        <div class="row justify-content-md-center">
          <div class="col-12 col-md-10 col-lg-8 col-xl-7">
            <h3 class="fs-6 mb-2 text-secondary text-center text-uppercase">What We Do?</h3>
            <h2 class="display-5 mb-1 mb-md-3 text-center">We offers exclusive dining experiences in your home.</h2>
            <hr class="w-50 mx-auto mb-2 mb-xl-5 border-dark-subtle">
          </div>
        </div>
      </div>

      <div class="container overflow-hidden">
        <div class="row gy-2 gy-md-0 gx-xxl-3">
          <div class="col-12 col-md-4">
            <div class="card bg-transparent border-0 rounded-0 overflow-hidden">
              <div class="card-body">
                <h3 class="h2 mb-2">Casual Dining</h3>
                <p class="mb-2 text-secondary">Whether you're marking a special occasion or just yearning for delicious cuisine, OSE Dining has you covered. Simply book us, and we'll bring our culinary expertise right to your doorstep.</p>
                <a href="{% url 'pages:casual_dining_success' %}" class="fw-bold text-decoration-none link-primary">
                  Casual Dining
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-short" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z" />
                  </svg>
                </a>
                <div class="bsb-circle bg-accent border border-4 border-accent position-absolute top-100 start-100 translate-middle"></div>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-4">
            <div class="card bg-transparent border-0 rounded-0 overflow-hidden">
              <div class="card-body">
                <h3 class="h2 mb-2">Fine Dining</h3>
                <p class="mb-2 text-secondary">Experience fine dining excellence with OSE. 
                  Our expertly crafted dishes and impeccable service promise a memorable culinary journey. 
                  Book us now and savor the sophistication in your space/home.</p>
                <a href="{% url 'pages:finedining' %}" class="fw-bold text-decoration-none link-primary">
                  Fine Dining
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-short" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z" />
                  </svg>
                </a>
                <div class="bsb-circle bg-accent border border-4 border-accent position-absolute top-100 start-100 translate-middle"></div>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-4">
            <div class="card bg-transparent border-0 rounded-0 overflow-hidden">

              <div class="card-body">
                <h3 class="h2 mb-2">Customised Dining</h3>
                <p class="mb-2 text-secondary">
                  We're delighted to offer personalized services through our professional, seasoned chefs to design menus or create excellent cuisine for you or your guests. 
                  Whether you're drawn to specific spices, dishes, cultures, or tastes, we provide a service that caters to your culinary desires.
                </p>
                <a href="{% url 'pages:customdining' %}" class="fw-bold text-decoration-none link-primary">
                  Custom Dining
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-short" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z" />
                  </svg>
                </a>
                <div class="bsb-circle bg-accent border border-4 border-accent position-absolute top-100 start-100 translate-middle"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  
      <!-- Section - About -->
      <!-- Process 1 - Bootstrap Brain Component -->
      <section id="scrollspyAbout" class="py-5 py-xl-8 bsb-section-py-xxl-1 bg-black text-white animate__animated">
        <div class="container">
          <div class="row justify-content-md-center">
            <div class="col-12 col-md-10 col-lg-8 col-xl-7">
              <h3 class="fs-6 mb-2 text-light text-center text-uppercase">Who Are We?</h3>
              <h2 class="display-5 mb-2 mb-md-3 text-center text-white">We offer bespoke private dining, bringing our kitchen to your home.</h2>
              <hr class="w-50 mx-auto mb-1 mb-xl-3 border-light-subtle">
            </div>
          </div>
        </div>
  
        <div class="container">
          <div class="row gy-5 gy-lg-0 align-items-lg-center">
            <div class="col-12 col-lg-6">
              <img class="img-fluid rounded" loading="lazy" src="https://i.ibb.co/3T8jXQ0/udoma.webp" alt="">
            </div>
            <div class="col-12 col-lg-6">
              <div class="row justify-content-xl-end">
                <div class="col-12 col-xl-11">
                    <p class="lead fs-10 mb-2 text-warning">The dining experience provided by OSE is characterized by intimacy, sensuality, and the creation of cherished memories. All in your desired space/location.</p>
                    <p class="mb-2">OSE Dining recognizes the cultural, traditional, and stylistic importance of food in everyone's lives, aiming to illuminate each individual's unique food narrative.</p>
                    <p class="mb-5">The culinary team at OSE is driven by a deep passion for excellence, crafting innovative recipes with dedication, affection, and extensive experience.</p>

                    <div class="row gy-4 gy-md-0 gx-xxl-5X">
                        <div class="col-12 col-md-6">
                          <div class="d-flex">
                            <div>
                              <h4 class="mb-3 text-warning">Our Magnificent Main Course</h4>
                              <p class="mb-0">We at OSE Private Dining, embodies exclusivity, cultural richness, and professional presentation. It's simple, tasteful, and elegant, with rich flavors that reflect our culinary excellence.</p>
                            </div>
                          </div>
                        </div>
                        <div class="col-12 col-md-6">
                          <div class="d-flex">
                            <div>
                              <h4 class="mb-3 text-warning">Dessert Glory</h4>
                              <p class="mb-0">Desserts, made with love and inspired by street snacks, heritage, and childhood tastes, offer memorable treats like banana cake bites, agbalumo syrup, kilishi gelato, and dankwa tuile.</p>
                            </div>
                          </div>
                        </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
</main>

<script>
  window.addEventListener('scroll', function() {
    const div = document.getElementById('scrollspyServices');
    const scrollspyAbout = document.getElementById('scrollspyAbout');
    const rect = div.getBoundingClientRect();
    const abt_rect = scrollspyAbout.getBoundingClientRect();
    
    // Check if the top and bottom of the div are within the viewport
    if (rect.top >= 0) {
      div.classList.add('animate__fadeInUp');
    } else if (abt_rect.top >= 0) {
      scrollspyAbout.classList.add('animate__fadeInUp');
    }
  });
</script>
{% endblock %}